name: SonarCloud analysis

on:
  push:
    branches: 
      - master
      - mejoras-calidad     
  pull_request:
    branches: 
      - master
      - mejoras-calidad
  workflow_dispatch:

permissions:
  pull-requests: read

jobs:
  Analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2.2.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} 
        with:
          args: >
            -Dsonar.projectKey=**DweskZ_neurolog-app**         # 👈 cambia por el Project Key real
            -Dsonar.organization=**dweskz**                    # 👈 cambia por tu Organization Key real
            -Dsonar.sources=.                                  # 👈 escanea todo el repo
            -Dsonar.branch.name=${{ github.ref_name }}         # 👈 detecta automáticamente la rama activa
